include = [
  { name = "options.output", value = "typescript", path = "typescript/" },
  { name = "options.output", value = "javascript", path = "javascript/" },
  { name = "options.output", value = "react-router", path = "react-router/" },
]